### ISSUE TITLE
empty molecule error

### ISSUE THREAD

**Issue by tantrev** [feiglab/locprefmd#2]
Greetings,

I've been trying to install prefmd that requires locprefmd, and have ran into the following errors when trying to run the `$LOCPREFMD/scripts/locprefmd.sh [INPUT PDB] > [REFINED PDB]` command:

```
PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /mnt/sdb1/root/Downloads/MolProbity/lib/sessions.php on line 129
PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /mnt/sdb1/root/Downloads/MolProbity/lib/sessions.php on line 130
PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /mnt/sdb1/root/Downloads/MolProbity/lib/sessions.php on line 133
PHP Warning:  session_name(): Cannot change session name when headers already sent in /mnt/sdb1/root/Downloads/MolProbity/lib/sessions.php on line 136
PHP Warning:  session_set_save_handler(): Cannot change save handler when headers already sent in /mnt/sdb1/root/Downloads/MolProbity/lib/sessions.php on line 138
No topology information available at /mnt/sdb1/root/Downloads/toolset/perl/CHARMM.pm line 884.
empty molecule, nothing to write at /mnt/sdb1/root/Downloads/toolset/perl/Molecule.pm line 980.
empty molecule, nothing to write at /mnt/sdb1/root/Downloads/toolset/perl/Molecule.pm line 980.
empty molecule, nothing to write at /mnt/sdb1/root/Downloads/toolset/perl/Molecule.pm line 980.
empty molecule, nothing to write at /mnt/sdb1/root/Downloads/toolset/perl/Molecule.pm line 980.
empty SICHO chain at /mnt/sdb1/root/Downloads/toolset/perl/Molecule.pm line 3539.
empty molecule, nothing to write at /mnt/sdb1/root/Downloads/toolset/perl/Molecule.pm line 980.
empty molecule, nothing to write at /mnt/sdb1/root/Downloads/toolset/perl/Molecule.pm line 980.
PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /mnt/sdb1/root/Downloads/MolProbity/lib/sessions.php on line 129
PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /mnt/sdb1/root/Downloads/MolProbity/lib/sessions.php on line 130
PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /mnt/sdb1/root/Downloads/MolProbity/lib/sessions.php on line 133
PHP Warning:  session_name(): Cannot change session name when headers already sent in /mnt/sdb1/root/Downloads/MolProbity/lib/sessions.php on line 136
PHP Warning:  session_set_save_handler(): Cannot change save handler when headers already sent in /mnt/sdb1/root/Downloads/MolProbity/lib/sessions.php on line 138
empty molecule at /mnt/sdb1/root/Downloads/toolset/perl/Molecule.pm line 1646.

```

The OS is Ubuntu v18 - any idea what's going on?  Any help would be more than appreciated.  Thank you in advance.

**Comment by feiglab** [comment]
The key issue is that CHARMM parameter/topology files are not accessible. 

Please check that LOCPREFMD set correctly and that the following two files are accessible on your system:
    $LOCPREFMD/data/xtra_top_all36_prot.rtf 
    $LOCPREFMD/data/xtrabonds2cmap_par_all36_prot.prm

**Comment by tantrev** [comment]
So I reinstalled everything and seem to have ran into a different issue this time.

The error output I received when running the following command may be viewed at this [link](https://pastebin.com/raw/qgDqpAdh):
> $LOCPREFMD/scripts/locprefmd.sh chimera_0.pdb

My /root/.bashrc file also has the following components:
```
export MMTSBDIR="/root/Downloads/toolset"
export PATH="/root/Downloads/toolset/perl:$PATH"
export PATH="/root/Downloads/toolset/bin:$PATH"
export CHARMMEXEC="/root/Downloads/charmm/charmm/exec/gnu/charmm"
export CHARMDATA="$LOCPREFMD/data"
export MOLPROBITY="/root/Downloads/molprobity/molprobity"
export LOCPREFMD="/root/Downloads/locprefmd"
```

Any idea what's going on?  Thank you in advance for the help.

**Comment by feiglab** [comment]
Difficult to tell without further information. What version of CHARMM do you have?

**Comment by huhlim** [comment]
I am not sure it is the reason for the error, but you missed one "M" at an environment variable, **CHARMMDATA**.

**Comment by tantrev** [comment]
Nice catch on the CHARMMDATA!  Thank you. I seem to have set it to the wrong path as well.  Unfortunately, I still seem to have some issues.

Here's the corrected /root/.bashrc lines:
```
export MMTSBDIR="/root/Downloads/toolset"
export PATH="/root/Downloads/toolset/perl:$PATH"
export PATH="/root/Downloads/toolset/bin:$PATH"
export CHARMMEXEC="/root/Downloads/charmm/charmm/exec/gnu/charmm"
export CHARMMDATA="/root/Downloads/charmm/charmm/toppar"
export MOLPROBITY="/root/Downloads/molprobity/molprobity"
export LOCPREFMD="/root/Downloads/locprefmd"
```

Regarding the CHARMM version, here's some sample output when I executed $CHARMMEXEC:

> Chemistry at HARvard Macromolecular Mechanics
>                 (CHARMM) - Free Version 44b2   February 15, 2020
>                                    686801d1a
>        Copyright(c) 1984-2020  President and Fellows of Harvard College
>                               All Rights Reserved
>   Current operating system: Linux-5.3.0-1020-gcp(x86_64)@xplor.c.murine-lt-hs
>                  Created on  5/28/20 at  1:31:02 by user: root

And here's a [link](https://pastebin.com/raw/aKpyUF8R) to what the output currently looks like when executing the following command:
`$LOCPREFMD/scripts/locprefmd.sh chimera_0.pdb`

If it makes any difference, I'd be more than happy to grant direct access to the machine via TurboVNC.  Sorry for the hassle.

**Comment by tantrev** [comment]
Should it also make any difference, I compiled and installed CHARMM with the following options:

`./install.com em64t lite`

Compiling with OpenMM was giving me some errors, so I figured I could probably get away with just the CPU support.  However, I'm more than happy to keep at-it with the OpenMM compile if it would help.

**Comment by feiglab** [comment]
Please recompile without the 'lite' option. I also recommend the GNU compiler.

So just try:

./install.com gnu

**Comment by tantrev** [comment]
Thanks for the tip.  I just tried that and some errors unfortunately still remain.  [Here's](https://pastebin.com/raw/JaQqMFND) a snapshot of the current error output.

**Comment by feiglab** [comment]
Yes. It's the same error. The CHARMM version you are using does not recognize the CMAP command. 
Please restart with an entirely clean install of CHARMM (from the original distribution file) and recompile with:
./install.com gnu

**Comment by tantrev** [comment]
Thank you - I was able to recompile successfully and that indeed seems to have fixed the CMAP errors.  Unfortunately, I still seem to be running into other issues.  The current error output may be accessed [here](https://pastebin.com/raw/9Mj9NufL).

**Comment by feiglab** [comment]
Can we take this offline, please? Send me an email: mfeiglab@gmail.com

**Comment by tantrev** [comment]
Will do, thanks for the help!
